version: '3.7'
services:
  db:
    image: postgres:14
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    volumes:
    - /home/nepogoda/PycharmProjects/test_FAPI/documents:/documents

#    healthcheck:
#        test: ["CMD", "pg_isready -U postgres -d postgres_1"]
#        interval: 10s
#        timeout: 5s
#        retries: 1


  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 9999:8000
    volumes:
    - /home/nepogoda/PycharmProjects/test_FAPI/documents:/documents  -
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ['/fastapi_app/docker/celery.sh', 'celery']
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: [ '/fastapi_app/docker/celery.sh', 'flower' ]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555



#Запускаем
# sudo docker compose build
# sudo docker compose up
